name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: [ '1.15.1' ]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d

      - name: Build for linux
        run: |
          go build -o build/Linux/NoodleX-linux .
          
      - name: Build for windows
        run: |
          env GOOS=windows GOARCH=amd64 go build -o build/Windows/NoodleX-windows.exe .
          
      - name: Upload linux
        uses: actions/upload-artifact@v2
        with:
          name: NoodleX-linux 
          path: ./build/Linux/NoodleX-linux
      
      - name: Upload Windows
        uses: actions/upload-artifact@v2
        with:
          name: NoodleX-windows
          path: ./build/Windows/NoodleX-windows.exe 
